### ISSUE TITLE
Compatibility with SvelteKit / SvelteKit兼容性

### ISSUE THREAD

**Issue by rakuzen25** [fengkx/svelte-aplayer#2]
请问这个库可以和SvelteKit一起用吗？貌似直接导入会出现`window is not defined`的问题。

**Comment by fengkx** [comment]
没试过 svelteKit 环境有什么特殊？

**Comment by rakuzen25** [comment]
> 没试过 svelteKit 环境有什么特殊？

默认是SSR（服务器端渲染），没法直接获取window。把SSR关掉倒是能用，但是会阻塞渲染，白屏一段时间。

**Comment by fengkx** [comment]
https://sapper.svelte.dev/docs#Third-party_libraries_that_depend_on_window

参考这种写法

**Comment by rakuzen25** [comment]
感谢！似乎SvelteKit没有这块documentation。之前有试过dynamic import，但是没试过`svelte:component`的写法。

晚些时候我再试一下，有问题再请教。

补充：找到了，但是在[FAQ](https://kit.svelte.dev/faq#integrations-how-do-i-use-a-client-side-only-library-that-depends-on-document-or-window)里……

**Comment by rakuzen25** [comment]
似乎还是有问题。

```svelte
<script lang="ts">
    import { onMount } from "svelte";
    import type { APlayerType } from "svelte-aplayer/dist/svelte/svelte-aplayer.es";

    let APlayer: APlayerType;

    onMount(async () => {
        APlayer = (await import("svelte-aplayer/dist/svelte/svelte-aplayer.es")).default;
        await import("svelte-aplayer/dist/svelte/style.css");
    });
</script>

<svelte:component
    this={APlayer}
    audio={{
        name: "君の知らない物語",
        artist: "supercell",
        cover: "https://blog-static.fengkx.top/svelte-aplayer/bakemonogatari-ed.jpg",
        url: "https://blog-static.fengkx.top/svelte-aplayer/bakemonogatari-ed.mp3",
    }}
/>
```

<details>
  <summary><code>aplayer.d.ts</code>（默认没提供貌似，我自己写的）</summary>

```typescript
declare module "svelte-aplayer" {
    export interface APlayerAudio {
        name: string;
        artist: string;
        url: string;
        cover: string;
        lrc: string;
        theme: string;
    }

    export interface APlayerProps {
        mini: boolean;
        autoplay: boolean;
        theme: string;
        loop: "all" | "one" | "none";
        order: "list" | "random";
        volume: number;
        audio: APlayerAudio[];
        mutex: boolean;
        list_folded: boolean;
        list_max_height: string;
        base_font_type: string;
    }
}

declare module "svelte-aplayer/dist/svelte/svelte-aplayer.es" {
    import { SvelteComponentTyped } from "svelte";

    export default class APlayer extends SvelteComponentTyped<APlayerProps> {}

    export type APlayerType = typeof APlayer;
}
```
</details>

然后浏览器报错`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'addEventListener')`。位置是`svelte-aplayer.es.js:1:28457`，不过我不是很确定这是源码的哪里。

外观上来看似乎能用，但我觉得应该还是有问题。能麻烦您看一下吗？

**Comment by david-bergman** [comment]
I am using SvelteKit and I get this error as well when the page loads, Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'addEventListener')
    at Et (svelte-aplayer.es.js:1:28457)

The component displays correctly, and plays, but any skipping for example throws further errors?

svelte-aplayer.es.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'getBoundingClientRect')

Is there any fix for this ?

**Comment by fengkx** [comment]
https://www.npmjs.com/package/svelte-aplayer/v/0.1.2 0.1.2 should fix this

**Comment by webdagger** [comment]
This issue still exists as of 0.1.2
